[package]
name = "todomvc"
version = "0.1.0"
authors = ["Jonathan Kingston <jonathan@jooped.co.uk>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
wasm-bindgen = { version = "0.2.23" }
web-sys = { version = "0.3.0", features = ['console', 'Element', 'Node', 'Window', 'HtmlElement', 'Document', 'HtmlDivElement', 'HtmlLabelElement', 'HtmlImageElement', 'HtmlInputElement', 'HtmlFormElement', 'HtmlTitleElement', 'HtmlBodyElement', 'HtmlHeadElement', 'HtmlMetaElement', 'HtmlButtonElement', 'HtmlTextAreaElement', 'HtmlSelectElement', 'HtmlBrElement', 'HtmlUListElement', 'HtmlOListElement', 'HtmlLiElement', 'HtmlHrElement', 'HtmlDListElement', 'HtmlOptionElement', 'HtmlCanvasElement', 'HtmlPreElement', 'HtmlFieldSetElement', 'HtmlSpanElement', 'HtmlParagraphElement', 'HtmlHtmlElement', 'HtmlFontElement', 'HtmlScriptElement', 'HtmlStyleElement', 'HtmlMapElement', 'HtmlSourceElement', 'HtmlDataElement', 'HtmlAreaElement', 'HtmlOutputElement', 'HtmlLinkElement', 'HtmlAnchorElement', 'HtmlEmbedElement', 'HtmlTableCellElement', 'HtmlLegendElement', 'HtmlTableRowElement', 'HtmlVideoElement', 'HtmlBaseElement', 'HtmlParamElement', 'HtmlTableSectionElement', 'HtmlOptGroupElement', 'HtmlTimeElement', 'HtmlFrameSetElement', 'HtmlDialogElement', 'HtmlDialogElement', 'HtmlMenuElement', 'HtmlObjectElement', 'HtmlSlotElement', 'HtmlTrackElement', 'HtmlMenuItemElement', 'HtmlModElement', 'HtmlIFrameElement', 'HtmlQuoteElement', 'HtmlFrameElement', 'HtmlTableElement', 'Storage', 'CssStyleDeclaration', 'DomTokenList', 'DomStringMap', 'Event', 'KeyboardEvent', 'EventTarget', 'NodeList', 'Location'] }
js-sys = { version = "0.3.0" }
